
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aws_utils"
version = "0.1.0"
dependencies = [
    "boto3==1.34.146",
    "aiofiles==24.1.0",
    "asyncio==3.4.3",
    "aiodns==3.2.0"
]

[tool.hatch.build.targets.wheel]
packages = ["src/aws_utils"]